services:
  app:
    build: .
    container_name: container_php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - minha-rede-no-docker

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=0000 
      - MYSQL_DATABASE=crudSimple
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=dbuser
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - minha-rede-no-docker

networks:
  minha-rede-no-docker:
    driver: bridge

volumes:
  mysqldata: